apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Access mode for the PVC
  resources:
    requests:
      storage: {{ .Values.cataloguedb.persistentVolume.storage }}
  storageClassName: {{ .Values.cataloguedb.persistentVolume.storageClassName | quote }}