---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-db
  labels:
    name: orders-db
spec:
  serviceName: "orders-db-service"
  replicas: 1
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
        - name: orders-db
          image: {{ if .Values.global.registry }}{{ .Values.global.registry }}/{{ end }}{{ .Values.ordersdb.image.repo }}:{{ .Values.ordersdb.image.tag }}
          ports:
            - name: mongo
              containerPort: 27017
          resources:
{{ toYaml .Values.ordersdb.resources | indent 12 }}
          securityContext:
            capabilities:
              drop:
                - all
              add:
                - CHOWN
                - SETGID
                - SETUID
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: ordersdb-mongo-pvc