apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-db-pvc
  labels:
    app: session-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.sessiondb.persistentVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.sessiondb.persistentVolume.size }}